version: '3'

services:

  db:
    image: mysql:latest
    container_name: mysqlDB
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=countryappdb
    ports:
      - 3306:3306
    restart: always

  countryApp:
    image: asapgroup/countryapp
    container_name: countryApp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/countryappdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor