version: '3'

services:

  db:
    image: postgres:latest
    container_name: countryDB
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=countryDB
    ports:
      - 5432:5432
    restart: always

  myApp:
    image: jakubpsz/countryapp
    container_name: countryapp
#        build:
#          context: .
#          dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/countryDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password